apiVersion: v1
kind: Service
metadata:
  name: feature-pipeline-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 11594
    protocol: TCP
    targetPort: 11594
  selector:
    app: feature-pipeline