apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: feature-pipeline
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: feature-pipeline
    spec:
      containers:
        - image: theblasiantj/feature_pipeline:0.1.1
          name: feature-pipeline
          ports:
            - containerPort: 11594
